e2e:
  - any:
      - changed-files:
          - any-glob-to-any-file: "packages/wrangler/e2e/**/*"
      - head-branch: "changeset-release/main"

c3-e2e:
  - any:
      - changed-files:
          - any-glob-to-any-file: "packages/create-cloudflare/e2e-tests/*"
      - head-branch: "changeset-release/main"
