##
# Configuration file for the Router Worker
#
# Please note that wrangler has a dependency on this file, and will
# attempt to read it as part of setting up a new Miniflare instance
# in developemnt mode. We should ensure that any configuration changes
# to this file are persisted in wrangler as well, when necessary.
# (see packages/wrangler/src/dev/miniflare.ts -> buildMiniflareOptions())
##
name = "router-worker"
account_id = "0f1b8aa119a907021f659042f95ea9ba"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2024-07-31"
compatibility_flags = ["nodejs_compat"]

[version_metadata]
binding = "VERSION_METADATA"

[[unsafe.bindings]]
name = "CONFIG"
type = "param"
param = "routerConfig"

[[unsafe.bindings]]
name = "ASSET_WORKER"
type = "internal_assets"
fetcherApi = "fetcher"

[[unsafe.bindings]]
name = "USER_WORKER"
type = "origin"

[unsafe.metadata.build_options]
stable_id = "cloudflare/cf_router_worker"
networks = ["cf","jdc"]

[[unsafe.bindings]]
name = "workers-router-worker"
type = "internal_capability_grants"