name = "devprod-status-bot"
main = "src/index.ts"
compatibility_date = "2023-09-29"
workers_dev = true
account_id = "e35fd947284363a46fd7061634477114"

[[rules]]
type = "Data"
globs = ["**/*.png"]

[triggers]
crons = [
  "0 10 * * MON-FRI",
  "0 10 * * TUE,THU",
  "0 15 * * MON,WED,FRI"
]

[ai]
binding = "AI"

[observability]
enabled = true