name: Auto-assign Issues

on:
  issues:
    types: [labeled]

jobs:
  assign-issue:
    runs-on: ubuntu-slim

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies
        with:
          node-version: 22 # need this version for `Set` methods
          pnpm-filters: "./tools"

      - name: Auto-assign issue
        run: node -r esbuild-register tools/github-workflow-helpers/auto-assign-issues.ts
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
