# Runs c3 e2e tests for quarantined frameworks on merges to main

name: C3 E2E (Quarantine)
on:
  pull_request:
    paths:
      - packages/create-cloudflare/**
  push:
    branches:
      - main
    paths:
      - packages/create-cloudflare/**

jobs:
  e2e:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.pm }}
      cancel-in-progress: true
    name: ${{ format('E2E ({0})', matrix.pm) }}
    if: ${{ github.repository_owner == 'cloudflare' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pm: [npm@0.0.0, pnpm@9.0.0, bun@1.0.3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: E2E Tests
        uses: ./.github/actions/run-c3-e2e
        with:
          packageManager: ${{ matrix.pm }}
          quarantine: true
          accountId: ${{ secrets.C3_TEST_CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.C3_TEST_CLOUDFLARE_API_TOKEN }}
