name: Add issues to DevProd project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/cloudflare/projects/1
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/cloudflare/projects/2
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: pages
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/cloudflare/projects/6
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: d1
