name: Wrangler startup

on:
  push:
    branches:
      - changeset-release/main

jobs:
  old-node:
    name: "Prevents old Node versions"
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js v10
        uses: actions/setup-node@v4
        with:
          node-version: 10.24.1

      - name: Check for error message
        run: node packages/wrangler/src/__tests__/test-old-node-version.js
  bun:
    name: "Prevents Bun"
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Check for error message
        run: node packages/wrangler/src/__tests__/test-bun.js
